import type { Metadata } from "next";
import Header from "./header"
import './i18next'
import  I18NProvider from './i18next/i18nProvider.jsx';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <I18NProvider>
          <Header />
          {children}
        </I18NProvider>
      </body>
    </html>
  );
}
